pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Mohan-mk06/Library-Management-system.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('Agille') {
                    bat 'npm install' 
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('Agille') {
                    // Added --no-cache to fix the "parent snapshot not found" error
                    bat 'docker build --no-cache -t library-app .' 
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                dir('Agille') {
                    // Points Jenkins to your local user config for Docker Desktop's Kubernetes
                    bat 'kubectl --kubeconfig="C:\\Users\\loges\\.kube\\config" config use-context docker-desktop'
                    bat 'kubectl --kubeconfig="C:\\Users\\loges\\.kube\\config" apply -f deployment.yaml'
                }
            }
        }
    }
}
